version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    
    steps:
      - checkout
      
      - run:
          name: depencies
          command: echo "Pau Nicolas"
